### ISSUE TITLE
 “(roam-block) No valid block here!” for embeds but not for refs

### ISSUE THREAD

**Issue by jonathan-sahar-tau** [Kinneyzhang/roam-block#15]
“(roam-block) No valid block here!” for embeds but not for refs
Hi,
when trying to store a block for embedding I get the above message, and no stack trace.
storing and inserting refs does work, however.

**Comment by Kinneyzhang** [comment]
A valid block means a block with a uuid overlay and the overlay is set every time when saving buffer. You could use "describe-text-properties" command when cursor is on a block to check if there is a uuid overlay. If none, save buffer and then try again. For org file, org headline is not included in a block.

**Comment by Kinneyzhang** [comment]
I will close this issue. If you still have a problem, please open a discussion.

**Comment by asayake-b5** [comment]
Hello,
I'm encountering the same issue.
It has nothing to do with saving, as some blocks can work while others do not in the same buffer. Besides, blocks do work, the problem seems to only appear with embeds (when references do work).

It also seems to work more or less depending on the selected text (in evil-mode, selecting the text with the basic visual mode seems to work better than selecting full lines), it still appears more or less random though, as the position of the cursor seems to be important.
